server:
  port: 8080
  servlet:
    context-path: /

spring:
  config:
    import: "classpath:application-db.yml" # RDS 연동

    hikari:
      maxLifeTime: 3590000
      maximum-pool-size: 30

# 기존 로컬 db
#  datasource:
#    driver-class-name: com.mysql.cj.jdbc.Driver
#    url: jdbc:mysql://localhost:3306/hufs_eval?characterEncoding=UTF-8&serverTimezone=UTC #listArticle TABLE 생성
#    username: root
#    password: 1234 #비밀번호

  profiles:
    include: API-KEY

  jpa:
    open-in-view: true
    hibernate:
      ddl-auto: create
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
      use-new-id-generator-mappings: false
    show-sql: true
    properties:
      hibernate.format_sql: true
      dialect: org.hibernate.dialect.MySQL8InnoDBDialect

logging:
  level:
    org.hibernate.SQL: debug